"""
Скрипт для заполнения таблицы activities.
Запуск: python ingest_activities.py [--skip-github]

Источники:
  - CURATED_ACTIVITIES — проверенный вручную список (как seed.py для universities).
  - GITHUB_SOURCES — реальный открытый список для школьников
    (JustinChavez/Pre-College-Opportunities). Не обновлялся с 2018 года,
    даты в нём без указания года — такие записи вставляются с verified=False
    и deadline=NULL, и не должны показываться студентам без ручной проверки
    (см. verified_only=True по умолчанию в GET /activities).
"""
import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))

import httpx

from app.database import supabase

CURATED_ACTIVITIES = [
    # ===== Стажировки =====
    {
        "title": "Google STEP Internship",
        "org": "Google",
        "category": "internship",
        "country": "США / Европа",
        "format": "Гибрид",
        "cost": "stipend",
        "cost_label": "Оплачиваемая",
        "grades": [11, 12],
        "level": "Продвинутый",
        "deadline": "2026-02-01",
        "duration": "12 недель, лето",
        "tags": ["CS", "Software Engineering", "Big Tech"],
        "prestige": 5,
        "about": "Программа Google для первокурсников и продвинутых старшеклассников. Реальные проекты с инженерными менторами, оплата + переезд.",
        "link": "https://buildyourfuture.withgoogle.com/programs/step/",
    },
    {
        "title": "Jane Street AMP",
        "org": "Jane Street",
        "category": "internship",
        "country": "Великобритания / США",
        "format": "Офлайн",
        "cost": "stipend",
        "cost_label": "Оплачиваемая",
        "grades": [11, 12],
        "level": "Продвинутый",
        "deadline": "2026-01-15",
        "duration": "5 недель, лето",
        "tags": ["Quant", "Finance", "Math", "CS"],
        "prestige": 5,
        "about": "Academy of Math and Programming — программа от ведущего quant-фонда. Идеально для тех, кто рассматривает количественные финансы.",
        "link": "https://www.janestreet.com/amp/",
    },
    {
        "title": "Школа анализа данных, Yandex",
        "org": "Yandex",
        "category": "internship",
        "country": "Казахстан / Онлайн",
        "format": "Гибрид",
        "cost": "free",
        "cost_label": "Бесплатно",
        "grades": [11, 12],
        "level": "Средний",
        "deadline": "2026-03-10",
        "duration": "8 недель",
        "tags": ["ML", "Data Science", "CS"],
        "prestige": 4,
        "about": "Интенсив по машинному обучению с лекциями инженеров Yandex и проектной работой. Сертификат + возможность стажировки.",
    },
    {
        "title": "Nazarbayev University CS Lab Intern",
        "org": "NU School of Engineering",
        "category": "internship",
        "country": "Казахстан",
        "format": "Офлайн",
        "cost": "free",
        "cost_label": "Бесплатно",
        "grades": [10, 11, 12],
        "level": "Средний",
        "deadline": "2026-04-20",
        "duration": "Лето, 6–10 недель",
        "tags": ["CS", "Research", "Local"],
        "prestige": 3,
        "about": "Стажировка в лабораториях NU. Подходит для усиления research-профиля в Казахстане до выпуска.",
    },
    # ===== Исследования =====
    {
        "title": "MIT PRIMES-USA",
        "org": "Massachusetts Institute of Technology",
        "category": "research",
        "country": "США / Удалённо",
        "format": "Онлайн",
        "cost": "free",
        "cost_label": "Бесплатно",
        "grades": [10, 11],
        "level": "Продвинутый",
        "deadline": "2025-11-30",
        "duration": "1 год, удалённо",
        "tags": ["Math", "CS", "Research", "Top-tier"],
        "prestige": 5,
        "about": "Годовая программа исследований по математике и CS под менторством PhD из MIT. Один из самых сильных research-проектов для школьников.",
        "link": "https://math.mit.edu/research/highschool/primes/usa.html",
    },
    {
        "title": "Research Science Institute (RSI)",
        "org": "CEE × MIT",
        "category": "research",
        "country": "США",
        "format": "Офлайн",
        "cost": "free",
        "cost_label": "Полностью покрыто",
        "grades": [11],
        "level": "Продвинутый",
        "deadline": "2026-01-12",
        "duration": "6 недель, лето",
        "tags": ["STEM", "Research", "Top-tier"],
        "prestige": 5,
        "about": "Самая престижная летняя research-программа в мире для школьников. Принимают ~80 человек глобально, полная стипендия.",
        "link": "https://www.cee.org/programs/research-science-institute",
    },
    {
        "title": "Pioneer Research Program",
        "org": "Pioneer Academics",
        "category": "research",
        "country": "Онлайн",
        "format": "Онлайн",
        "cost": "paid",
        "cost_label": "$6 500 (есть финпомощь)",
        "grades": [10, 11, 12],
        "level": "Средний",
        "deadline": "2026-02-28",
        "duration": "4 месяца",
        "tags": ["Research", "1-on-1", "Любая дисциплина"],
        "prestige": 4,
        "about": "Индивидуальный research-проект с профессором американского университета. Можно выбрать тему: AI, экономика, биология и др.",
        "link": "https://www.pioneeracademics.com/",
    },
    {
        "title": "Polygence Core",
        "org": "Polygence",
        "category": "research",
        "country": "Онлайн",
        "format": "Онлайн",
        "cost": "paid",
        "cost_label": "$2 500 (есть scholarships)",
        "grades": [9, 10, 11, 12],
        "level": "Начальный",
        "deadline": "2026-05-15",
        "duration": "10 встреч / 3 мес",
        "tags": ["Research", "Mentorship", "Любая тема"],
        "prestige": 3,
        "about": "Подбирают ментора-PhD под твою тему и за 3 месяца помогают довести research-проект до публикации или продукта.",
        "link": "https://www.polygence.org/",
    },
    # ===== Олимпиады =====
    # Даты не указываем: национальные отборочные туры назначает Минобр/оргкомитет
    # каждый год заново — фиксированная дата здесь была бы недостоверной.
    {
        "title": "International Olympiad in Informatics (IOI) — национальный отбор",
        "org": "IOI / Республиканская олимпиада по информатике",
        "category": "olympiad",
        "country": "Казахстан → международный этап",
        "format": "Офлайн",
        "cost": "free",
        "cost_label": "Бесплатно",
        "grades": [9, 10, 11, 12],
        "level": "Продвинутый",
        "deadline": None,
        "duration": "Отбор — учебный год, финал IOI — июль",
        "tags": ["CS", "Algorithms", "Olympiad", "Top-tier"],
        "prestige": 5,
        "about": "Путь на IOI идёт через республиканскую олимпиаду по информатике. Точные даты отборочных туров ежегодно устанавливает МОН РК — уточняй на сайте олимпиады.",
    },
    {
        "title": "International Mathematical Olympiad (IMO) — национальный отбор",
        "org": "IMO / Республиканская олимпиада по математике",
        "category": "olympiad",
        "country": "Казахстан → международный этап",
        "format": "Офлайн",
        "cost": "free",
        "cost_label": "Бесплатно",
        "grades": [9, 10, 11, 12],
        "level": "Продвинутый",
        "deadline": None,
        "duration": "Отбор — учебный год, финал IMO — июль",
        "tags": ["Math", "Olympiad", "Top-tier"],
        "prestige": 5,
        "about": "Классический сильный сигнал для топовых вузов по математике/CS. Отбор идёт через республиканскую олимпиаду, даты туров меняются год от года.",
    },
    {
        "title": "Conrad Challenge",
        "org": "Conrad Foundation",
        "category": "olympiad",
        "country": "Международный / Онлайн",
        "format": "Онлайн",
        "cost": "free",
        "cost_label": "Бесплатно",
        "grades": [9, 10, 11, 12],
        "level": "Средний",
        "deadline": None,
        "duration": "~5 месяцев, командный проект",
        "tags": ["Innovation", "STEM", "Entrepreneurship"],
        "prestige": 3,
        "about": "Командное соревнование инновационных STEM/бизнес-проектов с финалом на территории Kennedy Space Center. Даты сезона публикуются на сайте фонда каждый год.",
        "link": "https://www.conradchallenge.org/",
    },
    # ===== Волонтёрство =====
    {
        "title": "Habitat for Humanity — Global Village Youth Programs",
        "org": "Habitat for Humanity",
        "category": "volunteer",
        "country": "Международный",
        "format": "Офлайн",
        "cost": "paid",
        "cost_label": "Платно (взнос за поездку)",
        "grades": [10, 11, 12],
        "level": "Начальный",
        "deadline": None,
        "duration": "1–2 недели, выездная программа",
        "tags": ["Volunteering", "Community", "International"],
        "prestige": 3,
        "about": "Международные волонтёрские выезды на строительство жилья для нуждающихся семей. Приём заявок круглый год (rolling), даты поездок фиксированные.",
        "link": "https://www.habitat.org/volunteer/global-village",
    },
    {
        "title": "Key Club International",
        "org": "Kiwanis International",
        "category": "volunteer",
        "country": "Международный",
        "format": "Гибрид",
        "cost": "free",
        "cost_label": "Бесплатно",
        "grades": [9, 10, 11, 12],
        "level": "Начальный",
        "deadline": None,
        "duration": "Весь учебный год",
        "tags": ["Volunteering", "Leadership", "Community Service"],
        "prestige": 2,
        "about": "Крупнейшая школьная волонтёрская организация в мире — свой локальный клуб можно открыть при школе. Приём непрерывный (rolling).",
        "link": "https://www.keyclub.org/",
    },
]

# Источник: план работы РНПЦ «Дарын» на 2026 год (утверждён 25.12.2025).
# Из 220 пунктов плана отобраны только события, в которых участвует сам школьник
# (олимпиады, научные и творческие конкурсы, робототехника) — внутренние пункты
# центра (семинары для педагогов, медиарубрики, мониторинг, совещания) исключены.
# Даты не фиксируем: РНПЦ «Дарын» ежегодно уточняет точные даты этапов на своём сайте.
DARYN_2026_ACTIVITIES = [
    {
        'title': 'Международная олимпиада по физике (IPhO)',
        'org': 'IPhO / Республиканская олимпиада по физике',
        'category': 'olympiad',
        'country': 'Колумбия',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': 'Отбор — учебный год, финал — июль',
        'tags': ['Физика', 'Olympiad', 'Top-tier'],
        'prestige': 5,
        'about': 'Путь на IPhO идёт через республиканскую олимпиаду по физике. Один из самых престижных научных сигналов для инженерных и физических программ.',
    },
    {
        'title': 'Международная олимпиада по химии (IChO)',
        'org': 'IChO / Республиканская олимпиада по химии',
        'category': 'olympiad',
        'country': 'Ташкент, Узбекистан',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': 'Отбор — учебный год, финал — июль',
        'tags': ['Химия', 'Olympiad', 'Top-tier'],
        'prestige': 5,
        'about': 'Отбор в сборную идёт через республиканскую олимпиаду по химии, финал — среди сильнейших школьников мира.',
    },
    {
        'title': 'Международная олимпиада по биологии (IBO)',
        'org': 'IBO / Республиканская олимпиада по биологии',
        'category': 'olympiad',
        'country': 'Вильнюс, Литва',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': 'Отбор — учебный год, финал — июль',
        'tags': ['Биология', 'Olympiad', 'Top-tier'],
        'prestige': 5,
        'about': 'Ключевой международный трек для тех, кто целится в biology/pre-med программы.',
    },
    {
        'title': 'Международная олимпиада по экономике (IEO)',
        'org': 'IEO / Республиканская олимпиада по финансам и экономике',
        'category': 'olympiad',
        'country': 'Сучжоу, Китай',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': 'Отбор — учебный год, финал — июль',
        'tags': ['Экономика', 'Finance', 'Olympiad'],
        'prestige': 5,
        'about': 'Сильный сигнал для econ/business программ — отбор через республиканскую олимпиаду по финансам и экономике.',
    },
    {
        'title': 'Международная олимпиада по лингвистике (IOL)',
        'org': 'IOL / Республиканская лингвистическая олимпиада',
        'category': 'olympiad',
        'country': 'Бухарест, Румыния',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': 'Отбор — учебный год, финал — июль',
        'tags': ['Лингвистика', 'Olympiad'],
        'prestige': 5,
        'about': 'Олимпиада по решению лингвистических задач — ценится в liberal arts и computational linguistics программах.',
    },
    {
        'title': 'Международная олимпиада по географии (IGeO)',
        'org': 'IGeO / Республиканская олимпиада по общеобразовательным предметам',
        'category': 'olympiad',
        'country': 'Стамбул, Турция',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': 'Отбор — учебный год, финал — август',
        'tags': ['География', 'Olympiad'],
        'prestige': 5,
        'about': 'Международный трек для сильных школьников по географии и наукам о Земле.',
    },
    {
        'title': 'Европейская математическая олимпиада для девушек (EGMO)',
        'org': 'EGMO / Сборная Казахстана',
        'category': 'olympiad',
        'country': 'Бордо, Франция',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада апреля',
        'tags': ['Математика', 'Girls in STEM', 'Olympiad'],
        'prestige': 5,
        'about': 'Международная математическая олимпиада только для девушек — сильный и заметный для приёмных комиссий сигнал в STEM.',
    },
    {
        'title': 'Азиатская олимпиада по физике (APhO)',
        'org': 'APhO / Сборная Казахстана',
        'category': 'olympiad',
        'country': 'Пусан, Корея',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2–3-я декада мая',
        'tags': ['Физика', 'Olympiad'],
        'prestige': 4,
        'about': 'Региональный азиатский этап физической олимпиады, отбор идёт по итогам национальных сборов.',
    },
    {
        'title': 'Европейская олимпиада по физике (EuPhO)',
        'org': 'EuPhO / Сборная Казахстана',
        'category': 'olympiad',
        'country': 'Гётеборг, Швеция',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада июня',
        'tags': ['Физика', 'Olympiad'],
        'prestige': 4,
        'about': 'Европейский трек физической олимпиады для сборной олимпиадного резерва.',
    },
    {
        'title': 'Европейская олимпиада по географии (EGeO)',
        'org': 'EGeO / Сборная Казахстана',
        'category': 'olympiad',
        'country': 'Варна, Болгария',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '3-я декада июня – 1-я декада июля',
        'tags': ['География', 'Olympiad'],
        'prestige': 3,
        'about': 'Европейский региональный этап географической олимпиады.',
    },
    {
        'title': 'Балканская математическая олимпиада среди юношей (JBMO)',
        'org': 'JBMO / Сборная Казахстана',
        'category': 'olympiad',
        'country': 'Румыния',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10],
        'level': 'Средний',
        'deadline': None,
        'duration': '3-я декада июня – 1-я декада июля',
        'tags': ['Математика', 'Olympiad'],
        'prestige': 3,
        'about': 'Юниорский региональный этап Балканской математической олимпиады для младших классов.',
    },
    {
        'title': 'Международная олимпиада по естественным наукам среди юниоров (IJSO)',
        'org': 'IJSO / Сборная Казахстана',
        'category': 'olympiad',
        'country': 'уточняется',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [7, 8, 9],
        'level': 'Средний',
        'deadline': None,
        'duration': '3-я декада ноября',
        'tags': ['Физика', 'Химия', 'Биология', 'Olympiad'],
        'prestige': 4,
        'about': 'Комплексная олимпиада по естественным наукам для школьников до 15 лет — хороший ранний старт для будущих STEM-олимпиадников.',
    },
    {
        'title': 'Европейская юношеская олимпиада по информатике (EJOI)',
        'org': 'EJOI / Сборная Казахстана',
        'category': 'olympiad',
        'country': 'уточняется',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [8, 9, 10],
        'level': 'Средний',
        'deadline': None,
        'duration': '3-я декада августа',
        'tags': ['CS', 'Informatics', 'Olympiad'],
        'prestige': 3,
        'about': 'Юниорский трек информатической олимпиады для тех, кто ещё не готов к IOI, но уже сильнее школьного уровня.',
    },
    {
        'title': 'Международная математическая олимпиада «Шёлковый путь»',
        'org': 'Silk Road Mathematical Olympiad',
        'category': 'olympiad',
        'country': 'Алматы',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада марта',
        'tags': ['Математика', 'Olympiad'],
        'prestige': 4,
        'about': 'Международная математическая олимпиада, ежегодно принимающая участников в Алматы — хорошая тренировка перед IMO.',
    },
    {
        'title': 'Международная дистанционная Азиатско-Тихоокеанская математическая олимпиада (APMO)',
        'org': 'APMO',
        'category': 'olympiad',
        'country': 'Алматы (дистанционно)',
        'format': 'Онлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада марта',
        'tags': ['Математика', 'Olympiad'],
        'prestige': 4,
        'about': 'Дистанционный формат — участвовать можно из своей школы, результаты идут в общий олимпиадный рейтинг.',
    },
    {
        'title': 'Международная олимпиада по математике им. аль-Хорезми',
        'org': 'Al-Khwarizmi International Mathematical Olympiad',
        'category': 'olympiad',
        'country': 'Баку, Азербайджан',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2–3-я декада мая',
        'tags': ['Математика', 'Olympiad'],
        'prestige': 3,
        'about': 'Международная математическая олимпиада для команд стран-партнёров.',
    },
    {
        'title': 'Международная олимпиада по философии (IPO)',
        'org': 'International Philosophy Olympiad',
        'category': 'olympiad',
        'country': 'Бухарест, Румыния',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада мая',
        'tags': ['Философия', 'Critical Thinking', 'Olympiad'],
        'prestige': 4,
        'about': 'Эссе на заданную философскую тему на иностранном языке — ценится в liberal arts и humanities приёмных комиссиях.',
    },
    {
        'title': 'Международная Менделеевская олимпиада школьников по химии',
        'org': 'Mendeleev Chemistry Olympiad',
        'category': 'olympiad',
        'country': 'Москва, РФ',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '3-я декада апреля – 1-я декада мая',
        'tags': ['Химия', 'Olympiad'],
        'prestige': 4,
        'about': 'Одна из старейших международных химических олимпиад для школьников постсоветского пространства.',
    },
    {
        'title': 'Международная олимпиада «Туймаада» (математика, информатика, физика, химия)',
        'org': 'Туймаада',
        'category': 'olympiad',
        'country': 'Саха, Якутия',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '3-я декада июля',
        'tags': ['Математика', 'Физика', 'Химия', 'CS', 'Olympiad'],
        'prestige': 4,
        'about': 'Многопрофильная международная олимпиада — участие сразу по нескольким предметам естественно-математического цикла.',
    },
    {
        'title': 'Евразийская олимпиада по информатике (для стран ШОС)',
        'org': 'Eurasian Informatics Olympiad',
        'category': 'olympiad',
        'country': 'Алматы / Онлайн',
        'format': 'Гибрид',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2-я декада ноября – 2-я декада декабря',
        'tags': ['CS', 'Informatics', 'Olympiad'],
        'prestige': 3,
        'about': 'Отборочный и финальный этапы информатической олимпиады среди стран Шанхайской организации сотрудничества.',
    },
    {
        'title': 'Халықаралық «Қазақстан - Ата жұртым, Қасиетім - Ана тілім» олимпиадасы',
        'org': 'Международная олимпиада по казахскому языку и литературе для детей казахской диаспоры',
        'category': 'olympiad',
        'country': 'Щучинск, РОСО «Балдаурен»',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11],
        'level': 'Средний',
        'deadline': None,
        'duration': '3-я декада июня',
        'tags': ['Казахский язык', 'Литература', 'Olympiad'],
        'prestige': 3,
        'about': 'Олимпиада по казахскому языку и литературе специально для детей казахской диаспоры за рубежом.',
    },
    {
        'title': 'Международная олимпиада школьников по физике, химии и математике «Лаборатория подготовки талантов»',
        'org': 'Лаборатория подготовки талантов',
        'category': 'olympiad',
        'country': 'Баку, Азербайджан',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2–3-я декада декабря',
        'tags': ['Физика', 'Химия', 'Математика', 'Olympiad'],
        'prestige': 3,
        'about': 'Совместный проект стран-партнёров для подготовки олимпиадного резерва по трём точным наукам.',
    },
    {
        'title': 'Международная Жаутыковская олимпиада (математика, физика, информатика)',
        'org': 'Жаутыковская олимпиада',
        'category': 'olympiad',
        'country': 'Алматы',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада января',
        'tags': ['Математика', 'Физика', 'CS', 'Olympiad', 'Top-tier'],
        'prestige': 5,
        'about': 'Одна из самых престижных региональных олимпиад для специализированных школ — сильно котируется у технических вузов.',
    },
    {
        'title': 'Олимпиада по химии им. К. Сатпаева',
        'org': 'К. Сатпаев атындағы химия олимпиадасы',
        'category': 'olympiad',
        'country': 'Жезказган',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11],
        'level': 'Средний',
        'deadline': None,
        'duration': '3-я декада октября',
        'tags': ['Химия', 'Olympiad'],
        'prestige': 2,
        'about': 'Именная республиканская олимпиада по химии, названная в честь академика К. Сатпаева.',
    },
    {
        'title': 'Международное первенство по робототехнике «FIRST Global Challenge»',
        'org': 'FIRST Global',
        'category': 'olympiad',
        'country': 'США',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '3-я декада октября',
        'tags': ['Robotics', 'Engineering', 'Olympiad'],
        'prestige': 4,
        'about': 'Международный робототехнический чемпионат сборных команд стран — сильный extracurricular для инженерных программ.',
    },
    {
        'title': 'Республиканский конкурс научных проектов по робототехнике «FirstRobotics»',
        'org': 'FirstRobotics',
        'category': 'olympiad',
        'country': 'Астана',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2-я декада февраля',
        'tags': ['Robotics', 'Engineering'],
        'prestige': 3,
        'about': 'Республиканский отбор в области робототехники и инженерных проектов, открыт для всех возрастов школы.',
    },
    {
        'title': 'Фестиваль роботов',
        'org': 'РНПЦ «Дарын» / Университет им. С. Демиреля',
        'category': 'olympiad',
        'country': 'Каскелен',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        'level': 'Начальный',
        'deadline': None,
        'duration': '1-я декада января',
        'tags': ['Robotics'],
        'prestige': 2,
        'about': 'Фестиваль для обучающихся специализированных организаций образования — демонстрация инженерных проектов и роботов.',
    },
    {
        'title': 'Республиканский конкурс научных проектов (РГЖК/РНКП)',
        'org': 'Дарынды оқушылардың жобалық қызметі',
        'category': 'research',
        'country': 'Астана / Караганды',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [8, 9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада февраля',
        'tags': ['Research', 'Science Project'],
        'prestige': 4,
        'about': 'Флагманский республиканский конкурс научных проектов по естественно-математическому и общественно-гуманитарному направлениям.',
    },
    {
        'title': 'Национальный конкурс исследовательских проектов и творческих работ «ЗЕРДЕ»',
        'org': 'ЗЕРДЕ',
        'category': 'research',
        'country': 'Щучинск, РОСО «Балдаурен»',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [2, 3, 4, 5, 6, 7],
        'level': 'Начальный',
        'deadline': None,
        'duration': '3-я декада января / февраля',
        'tags': ['Research', 'Junior'],
        'prestige': 2,
        'about': 'Конкурс исследовательских проектов для младших и средних классов — хороший первый научный проект в портфолио.',
    },
    {
        'title': 'Международный конкурс исследовательских проектов по математике и механике им. У. Джолдасбекова',
        'org': 'Zholdasbekov International Research Contest',
        'category': 'research',
        'country': 'Астана',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '1-я декада марта',
        'tags': ['Math', 'Mechanics', 'Research'],
        'prestige': 4,
        'about': 'Именной международный конкурс исследовательских проектов по математике и механике для выпускных классов.',
    },
    {
        'title': 'Международные научные соревнования по космическим исследованиям «Открываем мир науки»',
        'org': 'Открываем мир науки',
        'category': 'research',
        'country': 'Астана',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада апреля',
        'tags': ['Space', 'STEM', 'Research'],
        'prestige': 3,
        'about': 'Конкурс проектов по космическим исследованиям для старшеклассников.',
    },
    {
        'title': 'Международные соревнования по науке и технике «ISEF Regeneron»',
        'org': 'Regeneron ISEF',
        'category': 'research',
        'country': 'Феникс, Аризона, США',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Продвинутый',
        'deadline': None,
        'duration': '2-я декада мая',
        'tags': ['STEM', 'Research', 'Top-tier'],
        'prestige': 5,
        'about': 'Крупнейшая в мире школьная научная ярмарка — путёвка на неё через аффилиацию на Regeneron ISEF считается одним из самых сильных научных достижений в заявке.',
    },
    {
        'title': 'Республиканский конкурс научно-творческих проектов «Әбіш оқулары»',
        'org': 'Әбіш оқулары',
        'category': 'research',
        'country': 'Актау',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2-я декада мая',
        'tags': ['Research', 'Creative Project'],
        'prestige': 2,
        'about': 'Именной республиканский конкурс научно-творческих проектов.',
    },
    {
        'title': 'Республиканский конкурс экологических проектов «ProEco»',
        'org': 'ProEco',
        'category': 'research',
        'country': 'Астана',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [5, 6, 7, 8],
        'level': 'Средний',
        'deadline': None,
        'duration': '3-я декада апреля',
        'tags': ['Ecology', 'Research'],
        'prestige': 2,
        'about': 'Конкурс экологических проектов для школьников среднего звена.',
    },
    {
        'title': 'Республиканский интеллектуальный конкурс юных историков «Менің кіші Отаным»',
        'org': 'Моя малая родина',
        'category': 'research',
        'country': 'Регионы / Астана',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10],
        'level': 'Средний',
        'deadline': None,
        'duration': '1-я декада октября',
        'tags': ['History', 'Research'],
        'prestige': 2,
        'about': 'Конкурс исследовательских работ по локальной истории для 9–10 классов, проходит в несколько этапов до республиканского финала.',
    },
    {
        'title': 'Республиканский конкурс «Мәшһүр Жүсіп оқулары»',
        'org': 'Мәшһүр Жүсіп оқулары',
        'category': 'olympiad',
        'country': 'Павлодар',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2-я декада мая',
        'tags': ['Литература', 'Творческий конкурс'],
        'prestige': 2,
        'about': 'Именной республиканский литературно-творческий конкурс.',
    },
    {
        'title': 'Республиканский конкурс «Ілияс оқулары»',
        'org': 'Ілияс оқулары',
        'category': 'olympiad',
        'country': 'Талдыкорган',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2-я декада мая',
        'tags': ['Литература', 'Творческий конкурс'],
        'prestige': 2,
        'about': 'Именной республиканский литературно-творческий конкурс.',
    },
    {
        'title': 'Конкурс «Мақатаев оқулары»',
        'org': 'Мақатаев оқулары',
        'category': 'olympiad',
        'country': 'Алматинская область',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2-я декада июня',
        'tags': ['Литература', 'Творческий конкурс'],
        'prestige': 2,
        'about': 'Именной республиканский литературно-творческий конкурс.',
    },
    {
        'title': 'Республиканский конкурс научно-творческих проектов «Мағжан оқулары»',
        'org': 'Мағжан оқулары',
        'category': 'research',
        'country': 'Петропавловск',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2-я декада июня',
        'tags': ['Литература', 'Research'],
        'prestige': 2,
        'about': 'Именной республиканский конкурс научно-творческих проектов.',
    },
    {
        'title': 'Республиканский творческий конкурс «АБАЙ ОҚУЛАРЫ»',
        'org': 'Абай оқулары',
        'category': 'olympiad',
        'country': 'Семей',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '2-я декада июня',
        'tags': ['Литература', 'Творческий конкурс'],
        'prestige': 3,
        'about': 'Крупный именной республиканский творческий конкурс в честь Абая Кунанбаева.',
    },
    {
        'title': 'Республиканский конкурс «Жыр алыбы - Жамбыл»',
        'org': 'Жыр алыбы - Жамбыл',
        'category': 'olympiad',
        'country': 'Алматинская область',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '1-я декада октября',
        'tags': ['Литература', 'Творческий конкурс'],
        'prestige': 2,
        'about': 'Именной республиканский литературно-творческий конкурс.',
    },
    {
        'title': 'Республиканский конкурс «Махамбет оқулары»',
        'org': 'Махамбет оқулары',
        'category': 'olympiad',
        'country': 'Атырау',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [9, 10, 11, 12],
        'level': 'Средний',
        'deadline': None,
        'duration': '1-я декада октября',
        'tags': ['Литература', 'Творческий конкурс'],
        'prestige': 2,
        'about': 'Именной республиканский литературно-творческий конкурс.',
    },
    {
        'title': 'Республиканский конкурс по ораторскому искусству и музыкальной импровизации «Ақберен»',
        'org': 'Ақберен',
        'category': 'olympiad',
        'country': 'Щучинск, РОСО «Балдаурен»',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        'level': 'Начальный',
        'deadline': None,
        'duration': '1-я декада ноября',
        'tags': ['Ораторское искусство', 'Творческий конкурс'],
        'prestige': 2,
        'about': 'Конкурс ораторского искусства и музыкальной импровизации для творческих школьников любого возраста.',
    },
    {
        'title': 'Интеллектуальная олимпиада «Ақбота»',
        'org': 'Ақбота',
        'category': 'olympiad',
        'country': 'Онлайн',
        'format': 'Онлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [5, 6, 7, 8, 9, 10, 11],
        'level': 'Начальный',
        'deadline': None,
        'duration': '3-я декада февраля / ноября',
        'tags': ['Общеобразовательные предметы', 'Онлайн'],
        'prestige': 2,
        'about': 'Онлайн-олимпиада по общественно-гуманитарному и естественно-математическому направлениям среди общеобразовательных школ.',
    },
    {
        'title': 'Игра-конкурс «Кенгуру»',
        'org': 'Kangaroo',
        'category': 'olympiad',
        'country': 'Онлайн',
        'format': 'Онлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        'level': 'Начальный',
        'deadline': None,
        'duration': '3-я декада марта',
        'tags': ['Математика', 'Онлайн', 'Junior'],
        'prestige': 1,
        'about': 'Массовая международная математическая игра-конкурс — хороший лёгкий старт для младших классов.',
    },
    {
        'title': 'Республиканская математическая олимпиада «БАСТАУ»',
        'org': 'БАСТАУ',
        'category': 'olympiad',
        'country': 'Алматы',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [2, 3, 4],
        'level': 'Начальный',
        'deadline': None,
        'duration': '3-я декада марта',
        'tags': ['Математика', 'Junior'],
        'prestige': 2,
        'about': 'Республиканская математическая олимпиада для 2–4 классов.',
    },
    {
        'title': 'Игра-конкурс по информатике «Bebras»',
        'org': 'Bebras',
        'category': 'olympiad',
        'country': 'Онлайн',
        'format': 'Онлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [3, 4, 5, 6, 7, 8, 9, 10, 11],
        'level': 'Начальный',
        'deadline': None,
        'duration': '3-я декада декабря',
        'tags': ['CS', 'Informatics', 'Онлайн'],
        'prestige': 1,
        'about': 'Международная онлайн-игра по информатике и алгоритмическому мышлению для широкого возрастного диапазона.',
    },
    {
        'title': 'Республиканский фестиваль «Шексіз өмір» для детей с особыми образовательными потребностями',
        'org': 'Шексіз өмір',
        'category': 'volunteer',
        'country': 'Астана',
        'format': 'Офлайн',
        'cost': 'free',
        'cost_label': 'Бесплатно',
        'grades': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        'level': 'Начальный',
        'deadline': None,
        'duration': '1-я декада мая',
        'tags': ['Inclusion', 'Community'],
        'prestige': 2,
        'about': 'Республиканский фестиваль для детей с особыми образовательными потребностями — инклюзивное мероприятие, полезное для volunteering/community секции профиля.',
    },
]

GITHUB_SOURCES = [
    {
        "name": "JustinChavez/Pre-College-Opportunities",
        "url": "https://raw.githubusercontent.com/JustinChavez/Pre-College-Opportunities/master/README.md",
    },
]


def parse_github_markdown_table(text: str, source_name: str) -> list[dict]:
    """Парсит таблицу `| Opportunity | Grades | Time | Location | App Deadline | Cost | Notes |`."""
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 5:
            continue
        first = cells[0]
        if first.lower() == "opportunity" or set(first) <= {"-", " ", ":"}:
            continue  # заголовок или строка-разделитель

        m = re.match(r"\[(.*?)\]\((.*?)\)", first)
        title = (m.group(1) if m else first).strip()
        link = m.group(2) if m else None
        if not title:
            continue

        grades_raw = cells[1] if len(cells) > 1 else ""
        grades = sorted({int(n) for n in re.findall(r"\b(9|10|11|12)\b", grades_raw)})
        cost_raw = cells[5] if len(cells) > 5 else ""

        rows.append({
            "title": title,
            "category": "research",  # источник смешивает research/STEM-программы, безопасный дефолт
            "country": cells[3] if len(cells) > 3 else None,
            "format": "Офлайн",
            "cost": "free" if "free" in cost_raw.lower() else "paid",
            "cost_label": cost_raw or None,
            "grades": grades or [9, 10, 11, 12],
            "deadline": None,  # в источнике даты без года — недостоверно, заполнять вручную
            "duration": cells[2] if len(cells) > 2 else None,
            "tags": ["STEM", "Summer Program"],
            "prestige": 2,
            "about": cells[6] if len(cells) > 6 else "",
            "link": link,
            "source": f"github:{source_name}",
            "verified": False,
        })
    return rows


def fetch_github_source(src: dict) -> list[dict]:
    resp = httpx.get(src["url"], timeout=15, follow_redirects=True)
    resp.raise_for_status()
    return parse_github_markdown_table(resp.text, src["name"])


def upsert(rows: list[dict]) -> tuple[int, int]:
    inserted = skipped = 0
    for row in rows:
        row.setdefault("source", "curated")
        row.setdefault("verified", True)
        payload = {k: v for k, v in row.items() if v is not None}
        existing = (
            supabase.table("activities")
            .select("id")
            .eq("title", row["title"])
            .eq("source", row["source"])
            .execute()
        )
        if existing.data:
            print(f"  SKIP  {row['title']} (уже есть)")
            skipped += 1
            continue
        try:
            supabase.table("activities").insert(payload).execute()
            tag = "" if row["verified"] else "  [unverified]"
            print(f"  OK    {row['title']} ({row['source']}){tag}")
            inserted += 1
        except Exception as e:
            print(f"  ERR   {row['title']}: {e}")
    return inserted, skipped


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--skip-github", action="store_true",
        help="Только curated-список, без запроса к внешним источникам",
    )
    args = parser.parse_args()

    print(f"Заполняем базу: {len(CURATED_ACTIVITIES)} проверенных активностей...")
    inserted, skipped = upsert(CURATED_ACTIVITIES)
    print(f"Curated: вставлено {inserted}, пропущено {skipped}")

    print(f"\nДобавляем {len(DARYN_2026_ACTIVITIES)} активностей из плана «Дарын» на 2026 год...")
    for row in DARYN_2026_ACTIVITIES:
        row.setdefault("source", "daryn-2026")
    inserted, skipped = upsert(DARYN_2026_ACTIVITIES)
    print(f"Дарын 2026: вставлено {inserted}, пропущено {skipped}")

    if not args.skip_github:
        for src in GITHUB_SOURCES:
            print(f"\nТянем из {src['name']} (verified=False — требует ручной проверки дедлайнов)...")
            try:
                rows = fetch_github_source(src)
            except Exception as e:
                print(f"  Не удалось получить {src['name']}: {e}")
                continue
            print(f"  Распарсено {len(rows)} записей")
            inserted, skipped = upsert(rows)
            print(f"  Вставлено {inserted}, пропущено {skipped}")


if __name__ == "__main__":
    main()
