"""
Скрипт для начального заполнения таблицы universities.
Запуск: python seed.py
"""
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from app.database import supabase

UNIVERSITIES = [
    # USA
    {
        "name": "MIT",
        "country": "USA",
        "qs_rank": 1,
        "acceptance_rate": 0.04,
        "sat_25th": 1510,
        "sat_75th": 1580,
        "avg_gpa": 4.17,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Mathematics", "Physics", "Engineering"],
        "deadline": "2027-01-01",
        "has_scholarship": True,
        "tuition_usd": 59750,
    },
    {
        "name": "Stanford University",
        "country": "USA",
        "qs_rank": 5,
        "acceptance_rate": 0.04,
        "sat_25th": 1500,
        "sat_75th": 1570,
        "avg_gpa": 3.96,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Engineering", "Business", "Economics", "Biology"],
        "deadline": "2027-01-05",
        "has_scholarship": True,
        "tuition_usd": 62484,
    },
    {
        "name": "Harvard University",
        "country": "USA",
        "qs_rank": 4,
        "acceptance_rate": 0.04,
        "sat_25th": 1460,
        "sat_75th": 1580,
        "avg_gpa": 3.9,
        "min_ielts": 7.0,
        "majors": ["Economics", "Biology", "Computer Science", "History", "Mathematics"],
        "deadline": "2027-01-01",
        "has_scholarship": True,
        "tuition_usd": 59320,
    },
    {
        "name": "Caltech",
        "country": "USA",
        "qs_rank": 6,
        "acceptance_rate": 0.04,
        "sat_25th": 1530,
        "sat_75th": 1580,
        "avg_gpa": 4.19,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Physics", "Mathematics", "Engineering", "Chemistry"],
        "deadline": "2027-01-03",
        "has_scholarship": True,
        "tuition_usd": 60864,
    },
    {
        "name": "Princeton University",
        "country": "USA",
        "qs_rank": 22,
        "acceptance_rate": 0.04,
        "sat_25th": 1500,
        "sat_75th": 1570,
        "avg_gpa": 3.9,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Economics", "Mathematics", "Engineering", "Public Policy"],
        "deadline": "2027-01-01",
        "has_scholarship": True,
        "tuition_usd": 59710,
    },
    {
        "name": "Carnegie Mellon University",
        "country": "USA",
        "qs_rank": 53,
        "acceptance_rate": 0.11,
        "sat_25th": 1480,
        "sat_75th": 1560,
        "avg_gpa": 3.89,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Engineering", "Design", "Business", "Mathematics"],
        "deadline": "2027-01-03",
        "has_scholarship": True,
        "tuition_usd": 61344,
    },
    {
        "name": "UC Berkeley",
        "country": "USA",
        "qs_rank": 10,
        "acceptance_rate": 0.14,
        "sat_25th": 1310,
        "sat_75th": 1530,
        "avg_gpa": 3.89,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Economics", "Biology", "Mathematics"],
        "deadline": "2026-11-30",
        "has_scholarship": True,
        "tuition_usd": 44066,
    },
    {
        "name": "Georgia Tech",
        "country": "USA",
        "qs_rank": 89,
        "acceptance_rate": 0.17,
        "sat_25th": 1370,
        "sat_75th": 1530,
        "avg_gpa": 4.07,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Business", "Architecture"],
        "deadline": "2027-01-06",
        "has_scholarship": True,
        "tuition_usd": 32876,
    },
    {
        "name": "University of Michigan",
        "country": "USA",
        "qs_rank": 33,
        "acceptance_rate": 0.20,
        "sat_25th": 1360,
        "sat_75th": 1530,
        "avg_gpa": 3.9,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Business", "Economics", "Biology"],
        "deadline": "2027-02-01",
        "has_scholarship": True,
        "tuition_usd": 52266,
    },
    {
        "name": "University of Texas at Austin",
        "country": "USA",
        "qs_rank": 136,
        "acceptance_rate": 0.29,
        "sat_25th": 1230,
        "sat_75th": 1450,
        "avg_gpa": 3.78,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Business", "Economics", "Communications"],
        "deadline": "2026-12-01",
        "has_scholarship": False,
        "tuition_usd": 38326,
    },
    # UK
    {
        "name": "University of Cambridge",
        "country": "UK",
        "qs_rank": 2,
        "acceptance_rate": 0.21,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 4.0,
        "min_ielts": 7.5,
        "majors": ["Computer Science", "Mathematics", "Physics", "Engineering", "Economics"],
        "deadline": "2026-10-15",
        "has_scholarship": True,
        "tuition_usd": 45860,
    },
    {
        "name": "University of Oxford",
        "country": "UK",
        "qs_rank": 3,
        "acceptance_rate": 0.17,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 4.0,
        "min_ielts": 7.5,
        "majors": ["Computer Science", "Mathematics", "Physics", "Economics", "Law"],
        "deadline": "2026-10-15",
        "has_scholarship": True,
        "tuition_usd": 45860,
    },
    {
        "name": "Imperial College London",
        "country": "UK",
        "qs_rank": 8,
        "acceptance_rate": 0.14,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.9,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Physics", "Business"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 42000,
    },
    {
        "name": "UCL",
        "country": "UK",
        "qs_rank": 9,
        "acceptance_rate": 0.63,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Economics", "Law", "Mathematics"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 35000,
    },
    # Switzerland
    {
        "name": "ETH Zürich",
        "country": "Switzerland",
        "qs_rank": 7,
        "acceptance_rate": 0.27,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 4.0,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Physics", "Architecture"],
        "deadline": "2026-12-15",
        "has_scholarship": False,
        "tuition_usd": 1460,
    },
    {
        "name": "EPFL",
        "country": "Switzerland",
        "qs_rank": 17,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.9,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Physics"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 1460,
    },
    # Netherlands
    {
        "name": "TU Delft",
        "country": "Netherlands",
        "qs_rank": 49,
        "acceptance_rate": 0.65,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Architecture", "Applied Mathematics"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 15000,
    },
    {
        "name": "University of Amsterdam",
        "country": "Netherlands",
        "qs_rank": 53,
        "acceptance_rate": 0.55,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Economics", "Law", "Psychology", "Business"],
        "deadline": "2027-02-01",
        "has_scholarship": False,
        "tuition_usd": 12000,
    },
    # Germany
    {
        "name": "TU Munich",
        "country": "Germany",
        "qs_rank": 30,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Physics", "Business"],
        "deadline": "2027-01-31",
        "has_scholarship": False,
        "tuition_usd": 300,
    },
    # Canada
    {
        "name": "University of Toronto",
        "country": "Canada",
        "qs_rank": 25,
        "acceptance_rate": 0.43,
        "sat_25th": 1240,
        "sat_75th": 1440,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Economics", "Biology"],
        "deadline": "2027-01-13",
        "has_scholarship": True,
        "tuition_usd": 48040,
    },
    {
        "name": "McGill University",
        "country": "Canada",
        "qs_rank": 46,
        "acceptance_rate": 0.41,
        "sat_25th": 1220,
        "sat_75th": 1420,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Medicine", "Law", "Economics"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 30000,
    },
    # Singapore
    {
        "name": "NUS",
        "country": "Singapore",
        "qs_rank": 8,
        "acceptance_rate": 0.20,
        "sat_25th": 1350,
        "sat_75th": 1530,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Business", "Medicine", "Law"],
        "deadline": "2027-02-28",
        "has_scholarship": True,
        "tuition_usd": 28000,
    },
    # Australia
    {
        "name": "University of Melbourne",
        "country": "Australia",
        "qs_rank": 14,
        "acceptance_rate": 0.70,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Business", "Law", "Medicine"],
        "deadline": "2026-10-31",
        "has_scholarship": True,
        "tuition_usd": 38000,
    },
    # South Korea
    {
        "name": "KAIST",
        "country": "South Korea",
        "qs_rank": 56,
        "acceptance_rate": 0.25,
        "sat_25th": 1350,
        "sat_75th": 1510,
        "avg_gpa": 3.9,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Physics"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 8000,
    },
    # Japan
    {
        "name": "University of Tokyo",
        "country": "Japan",
        "qs_rank": 32,
        "acceptance_rate": 0.33,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Economics", "Law"],
        "deadline": "2027-01-31",
        "has_scholarship": True,
        "tuition_usd": 5000,
    },
    # USA (batch 2)
    {
        "name": "Yale University",
        "country": "USA",
        "qs_rank": 16,
        "acceptance_rate": 0.045,
        "sat_25th": 1460,
        "sat_75th": 1580,
        "avg_gpa": 4.14,
        "min_ielts": 7.0,
        "majors": ["Political Science", "Economics", "History", "Biology", "Computer Science"],
        "deadline": "2027-01-02",
        "has_scholarship": True,
        "tuition_usd": 64700,
    },
    {
        "name": "Columbia University",
        "country": "USA",
        "qs_rank": 18,
        "acceptance_rate": 0.04,
        "sat_25th": 1470,
        "sat_75th": 1560,
        "avg_gpa": 4.0,
        "min_ielts": 7.0,
        "majors": ["Economics", "Computer Science", "Political Science", "Engineering", "English"],
        "deadline": "2027-01-01",
        "has_scholarship": True,
        "tuition_usd": 68400,
    },
    {
        "name": "University of Pennsylvania",
        "country": "USA",
        "qs_rank": 13,
        "acceptance_rate": 0.06,
        "sat_25th": 1500,
        "sat_75th": 1560,
        "avg_gpa": 3.9,
        "min_ielts": 7.0,
        "majors": ["Business", "Economics", "Computer Science", "Nursing", "Engineering"],
        "deadline": "2027-01-05",
        "has_scholarship": True,
        "tuition_usd": 66100,
    },
    {
        "name": "Cornell University",
        "country": "USA",
        "qs_rank": 20,
        "acceptance_rate": 0.07,
        "sat_25th": 1450,
        "sat_75th": 1560,
        "avg_gpa": 4.07,
        "min_ielts": 7.0,
        "majors": ["Engineering", "Agriculture", "Business", "Computer Science", "Hospitality"],
        "deadline": "2027-01-02",
        "has_scholarship": True,
        "tuition_usd": 64510,
    },
    {
        "name": "University of Chicago",
        "country": "USA",
        "qs_rank": 11,
        "acceptance_rate": 0.05,
        "sat_25th": 1500,
        "sat_75th": 1570,
        "avg_gpa": 4.0,
        "min_ielts": 7.0,
        "majors": ["Economics", "Mathematics", "Political Science", "Biology", "Computer Science"],
        "deadline": "2027-01-02",
        "has_scholarship": True,
        "tuition_usd": 65985,
    },
    {
        "name": "Duke University",
        "country": "USA",
        "qs_rank": 52,
        "acceptance_rate": 0.06,
        "sat_25th": 1490,
        "sat_75th": 1570,
        "avg_gpa": 4.13,
        "min_ielts": 7.0,
        "majors": ["Economics", "Public Policy", "Biology", "Computer Science", "Engineering"],
        "deadline": "2027-01-02",
        "has_scholarship": True,
        "tuition_usd": 63054,
    },
    {
        "name": "Northwestern University",
        "country": "USA",
        "qs_rank": 47,
        "acceptance_rate": 0.07,
        "sat_25th": 1470,
        "sat_75th": 1550,
        "avg_gpa": 4.1,
        "min_ielts": 7.0,
        "majors": ["Journalism", "Economics", "Computer Science", "Engineering", "Theatre"],
        "deadline": "2027-01-02",
        "has_scholarship": True,
        "tuition_usd": 65964,
    },
    {
        "name": "Johns Hopkins University",
        "country": "USA",
        "qs_rank": 28,
        "acceptance_rate": 0.07,
        "sat_25th": 1520,
        "sat_75th": 1560,
        "avg_gpa": 3.92,
        "min_ielts": 7.0,
        "majors": ["Biomedical Engineering", "Public Health", "International Studies", "Computer Science", "Neuroscience"],
        "deadline": "2027-01-02",
        "has_scholarship": True,
        "tuition_usd": 62840,
    },
    {
        "name": "UCLA",
        "country": "USA",
        "qs_rank": 40,
        "acceptance_rate": 0.09,
        "sat_25th": 1290,
        "sat_75th": 1530,
        "avg_gpa": 4.18,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Economics", "Psychology", "Business Economics", "Film"],
        "deadline": "2026-11-30",
        "has_scholarship": True,
        "tuition_usd": 46503,
    },
    {
        "name": "UC San Diego",
        "country": "USA",
        "qs_rank": 63,
        "acceptance_rate": 0.24,
        "sat_25th": 1300,
        "sat_75th": 1500,
        "avg_gpa": 4.0,
        "min_ielts": 7.0,
        "majors": ["Computer Science", "Biology", "Engineering", "Economics", "Data Science"],
        "deadline": "2026-11-30",
        "has_scholarship": False,
        "tuition_usd": 46431,
    },
    {
        "name": "University of Washington",
        "country": "USA",
        "qs_rank": 72,
        "acceptance_rate": 0.45,
        "sat_25th": 1250,
        "sat_75th": 1470,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Business", "Biology", "Informatics"],
        "deadline": "2026-11-15",
        "has_scholarship": False,
        "tuition_usd": 42576,
    },
    {
        "name": "New York University",
        "country": "USA",
        "qs_rank": 39,
        "acceptance_rate": 0.08,
        "sat_25th": 1440,
        "sat_75th": 1560,
        "avg_gpa": 3.7,
        "min_ielts": 7.0,
        "majors": ["Business", "Film", "Computer Science", "Economics", "Journalism"],
        "deadline": "2027-01-05",
        "has_scholarship": True,
        "tuition_usd": 62796,
    },
    {
        "name": "University of Illinois Urbana-Champaign",
        "country": "USA",
        "qs_rank": 69,
        "acceptance_rate": 0.45,
        "sat_25th": 1330,
        "sat_75th": 1500,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Business", "Agriculture", "Accounting"],
        "deadline": "2026-11-01",
        "has_scholarship": False,
        "tuition_usd": 36122,
    },
    {
        "name": "Purdue University",
        "country": "USA",
        "qs_rank": 113,
        "acceptance_rate": 0.53,
        "sat_25th": 1200,
        "sat_75th": 1440,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Computer Science", "Agriculture", "Aviation", "Business"],
        "deadline": "2026-11-01",
        "has_scholarship": False,
        "tuition_usd": 29334,
    },
    {
        "name": "University of Wisconsin-Madison",
        "country": "USA",
        "qs_rank": 64,
        "acceptance_rate": 0.43,
        "sat_25th": 1330,
        "sat_75th": 1480,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Business", "Computer Science", "Journalism", "Biology"],
        "deadline": "2027-02-01",
        "has_scholarship": False,
        "tuition_usd": 40390,
    },
    # UK (batch 2)
    {
        "name": "London School of Economics",
        "country": "UK",
        "qs_rank": 45,
        "acceptance_rate": 0.09,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.9,
        "min_ielts": 7.0,
        "majors": ["Economics", "Law", "Political Science", "International Relations", "Finance"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 34000,
    },
    {
        "name": "University of Edinburgh",
        "country": "UK",
        "qs_rank": 27,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Law", "Medicine", "Computer Science", "Economics", "History"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 35000,
    },
    {
        "name": "King's College London",
        "country": "UK",
        "qs_rank": 31,
        "acceptance_rate": 0.13,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 7.0,
        "majors": ["Law", "Medicine", "International Relations", "Computer Science", "Business"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 36000,
    },
    {
        "name": "University of Manchester",
        "country": "UK",
        "qs_rank": 34,
        "acceptance_rate": 0.56,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Business", "Computer Science", "Chemistry", "Law"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 32000,
    },
    {
        "name": "University of Bristol",
        "country": "UK",
        "qs_rank": 61,
        "acceptance_rate": 0.60,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Law", "Economics", "Computer Science", "Biology"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 30000,
    },
    # Canada (batch 2)
    {
        "name": "University of British Columbia",
        "country": "Canada",
        "qs_rank": 34,
        "acceptance_rate": 0.53,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Business", "Biology", "Arts"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 42000,
    },
    {
        "name": "University of Waterloo",
        "country": "Canada",
        "qs_rank": 112,
        "acceptance_rate": 0.53,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Mathematics", "Business", "Actuarial Science"],
        "deadline": "2027-02-01",
        "has_scholarship": True,
        "tuition_usd": 45000,
    },
    {
        "name": "University of Alberta",
        "country": "Canada",
        "qs_rank": 111,
        "acceptance_rate": 0.58,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Business", "Computer Science", "Medicine", "Agriculture"],
        "deadline": "2027-03-01",
        "has_scholarship": True,
        "tuition_usd": 30000,
    },
    # Australia (batch 2)
    {
        "name": "University of Sydney",
        "country": "Australia",
        "qs_rank": 19,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Law", "Medicine", "Business", "Engineering", "Arts"],
        "deadline": "2026-12-15",
        "has_scholarship": True,
        "tuition_usd": 40000,
    },
    {
        "name": "Australian National University",
        "country": "Australia",
        "qs_rank": 30,
        "acceptance_rate": 0.35,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Political Science", "Law", "Economics", "Computer Science", "International Relations"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 42000,
    },
    {
        "name": "University of New South Wales",
        "country": "Australia",
        "qs_rank": 19,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Business", "Computer Science", "Law", "Medicine"],
        "deadline": "2026-12-15",
        "has_scholarship": True,
        "tuition_usd": 41000,
    },
    {
        "name": "Monash University",
        "country": "Australia",
        "qs_rank": 37,
        "acceptance_rate": 0.45,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.5,
        "majors": ["Business", "Engineering", "Medicine", "Pharmacy", "IT"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 38000,
    },
    # Germany (batch 2)
    {
        "name": "LMU Munich",
        "country": "Germany",
        "qs_rank": 59,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Law", "Medicine", "Business", "Physics", "Computer Science"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 300,
    },
    {
        "name": "Heidelberg University",
        "country": "Germany",
        "qs_rank": 87,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Medicine", "Physics", "Law", "Biology", "Chemistry"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 300,
    },
    {
        "name": "Humboldt University of Berlin",
        "country": "Germany",
        "qs_rank": 127,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Law", "Economics", "Humanities", "Social Sciences", "Computer Science"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 300,
    },
    {
        "name": "RWTH Aachen University",
        "country": "Germany",
        "qs_rank": 99,
        "acceptance_rate": 0.45,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Computer Science", "Mathematics", "Physics", "Business"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 300,
    },
    # France
    {
        "name": "Sorbonne University",
        "country": "France",
        "qs_rank": 63,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Medicine", "Law", "Humanities", "Sciences", "Engineering"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 3000,
    },
    {
        "name": "PSL University",
        "country": "France",
        "qs_rank": 24,
        "acceptance_rate": 0.20,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Sciences", "Humanities", "Engineering", "Economics", "Arts"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 4000,
    },
    {
        "name": "École Polytechnique",
        "country": "France",
        "qs_rank": 46,
        "acceptance_rate": 0.05,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.9,
        "min_ielts": 7.0,
        "majors": ["Engineering", "Mathematics", "Physics", "Computer Science", "Economics"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 15000,
    },
    {
        "name": "Sciences Po",
        "country": "France",
        "qs_rank": 78,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Political Science", "International Relations", "Law", "Economics", "Journalism"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 15000,
    },
    # Switzerland (batch 2)
    {
        "name": "University of Zurich",
        "country": "Switzerland",
        "qs_rank": 80,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Medicine", "Law", "Economics", "Psychology", "Biology"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 2000,
    },
    # Netherlands (batch 2)
    {
        "name": "Leiden University",
        "country": "Netherlands",
        "qs_rank": 68,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Law", "Humanities", "Social Sciences", "Computer Science", "Psychology"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 13000,
    },
    {
        "name": "Utrecht University",
        "country": "Netherlands",
        "qs_rank": 75,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Medicine", "Law", "Sciences", "Humanities", "Economics"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 13000,
    },
    # Sweden
    {
        "name": "KTH Royal Institute of Technology",
        "country": "Sweden",
        "qs_rank": 78,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Computer Science", "Architecture", "Mathematics", "Physics"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 18000,
    },
    {
        "name": "Lund University",
        "country": "Sweden",
        "qs_rank": 85,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.5,
        "majors": ["Law", "Economics", "Engineering", "Medicine", "Social Sciences"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 16000,
    },
    # Denmark
    {
        "name": "University of Copenhagen",
        "country": "Denmark",
        "qs_rank": 96,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Medicine", "Law", "Sciences", "Humanities", "Social Sciences"],
        "deadline": "2027-03-15",
        "has_scholarship": False,
        "tuition_usd": 16000,
    },
    # Norway
    {
        "name": "University of Oslo",
        "country": "Norway",
        "qs_rank": 101,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.5,
        "majors": ["Law", "Medicine", "Sciences", "Humanities", "Social Sciences"],
        "deadline": "2026-12-01",
        "has_scholarship": False,
        "tuition_usd": 13000,
    },
    # Finland
    {
        "name": "University of Helsinki",
        "country": "Finland",
        "qs_rank": 104,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Law", "Medicine", "Sciences", "Social Sciences", "Computer Science"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 13000,
    },
    # Italy
    {
        "name": "Politecnico di Milano",
        "country": "Italy",
        "qs_rank": 123,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Architecture", "Design", "Computer Science", "Business"],
        "deadline": "2027-02-01",
        "has_scholarship": True,
        "tuition_usd": 4000,
    },
    {
        "name": "Bocconi University",
        "country": "Italy",
        "qs_rank": 150,
        "acceptance_rate": 0.20,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Economics", "Finance", "Management", "Law", "Data Science"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 17000,
    },
    # Spain
    {
        "name": "University of Barcelona",
        "country": "Spain",
        "qs_rank": 168,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.0,
        "majors": ["Medicine", "Law", "Business", "Humanities", "Psychology"],
        "deadline": "2027-03-01",
        "has_scholarship": False,
        "tuition_usd": 3000,
    },
    {
        "name": "Universidad Autónoma de Madrid",
        "country": "Spain",
        "qs_rank": 200,
        "acceptance_rate": 0.55,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.4,
        "min_ielts": 6.0,
        "majors": ["Law", "Economics", "Medicine", "Sciences", "Psychology"],
        "deadline": "2027-03-01",
        "has_scholarship": False,
        "tuition_usd": 2500,
    },
    # Ireland
    {
        "name": "Trinity College Dublin",
        "country": "Ireland",
        "qs_rank": 87,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Law", "Medicine", "Computer Science", "Business", "Arts"],
        "deadline": "2027-02-01",
        "has_scholarship": False,
        "tuition_usd": 25000,
    },
    # Belgium
    {
        "name": "KU Leuven",
        "country": "Belgium",
        "qs_rank": 60,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Law", "Medicine", "Engineering", "Sciences", "Business"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 6000,
    },
    # Austria
    {
        "name": "University of Vienna",
        "country": "Austria",
        "qs_rank": 130,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.0,
        "majors": ["Law", "Medicine", "Humanities", "Sciences", "Social Sciences"],
        "deadline": "2027-09-01",
        "has_scholarship": False,
        "tuition_usd": 1700,
    },
    # China
    {
        "name": "Tsinghua University",
        "country": "China",
        "qs_rank": 20,
        "acceptance_rate": 0.02,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.9,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "majors": ["Engineering", "Computer Science", "Economics", "Architecture", "Physics"],
        "deadline": "2027-02-28",
        "has_scholarship": True,
        "tuition_usd": 5000,
    },
    {
        "name": "Peking University",
        "country": "China",
        "qs_rank": 14,
        "acceptance_rate": 0.02,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.9,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "majors": ["Economics", "Law", "Humanities", "Computer Science", "Medicine"],
        "deadline": "2027-02-28",
        "has_scholarship": True,
        "tuition_usd": 5000,
    },
    {
        "name": "Fudan University",
        "country": "China",
        "qs_rank": 30,
        "acceptance_rate": 0.05,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "majors": ["Economics", "Journalism", "Computer Science", "Medicine", "International Relations"],
        "deadline": "2027-03-31",
        "has_scholarship": True,
        "tuition_usd": 5500,
    },
    {
        "name": "Shanghai Jiao Tong University",
        "country": "China",
        "qs_rank": 47,
        "acceptance_rate": 0.05,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "min_toefl": 90,
        "majors": ["Engineering", "Medicine", "Computer Science", "Business", "Physics"],
        "deadline": "2027-03-31",
        "has_scholarship": True,
        "tuition_usd": 5500,
    },
    # Hong Kong
    {
        "name": "University of Hong Kong",
        "country": "Hong Kong",
        "qs_rank": 17,
        "acceptance_rate": 0.10,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Business", "Law", "Medicine", "Computer Science", "Arts"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 22000,
    },
    {
        "name": "Hong Kong University of Science and Technology",
        "country": "Hong Kong",
        "qs_rank": 40,
        "acceptance_rate": 0.15,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Business", "Computer Science", "Science", "Design"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 20000,
    },
    {
        "name": "Chinese University of Hong Kong",
        "country": "Hong Kong",
        "qs_rank": 36,
        "acceptance_rate": 0.15,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Medicine", "Business", "Law", "Computer Science", "Social Sciences"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 20000,
    },
    # Japan (batch 2)
    {
        "name": "Kyoto University",
        "country": "Japan",
        "qs_rank": 45,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Sciences", "Law", "Economics", "Medicine"],
        "deadline": "2027-01-31",
        "has_scholarship": True,
        "tuition_usd": 5000,
    },
    {
        "name": "Osaka University",
        "country": "Japan",
        "qs_rank": 68,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Medicine", "Sciences", "Economics", "Law"],
        "deadline": "2027-01-31",
        "has_scholarship": True,
        "tuition_usd": 5000,
    },
    # South Korea (batch 2)
    {
        "name": "Seoul National University",
        "country": "South Korea",
        "qs_rank": 31,
        "acceptance_rate": 0.15,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Business", "Law", "Medicine", "Computer Science"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 7000,
    },
    {
        "name": "Yonsei University",
        "country": "South Korea",
        "qs_rank": 76,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.0,
        "majors": ["Business", "Medicine", "Engineering", "International Studies", "Law"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 9000,
    },
    # Singapore (batch 2)
    {
        "name": "Nanyang Technological University",
        "country": "Singapore",
        "qs_rank": 15,
        "acceptance_rate": 0.25,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.7,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Business", "Computer Science", "Design", "Medicine"],
        "deadline": "2027-02-28",
        "has_scholarship": True,
        "tuition_usd": 27000,
    },
    # Taiwan
    {
        "name": "National Taiwan University",
        "country": "Taiwan",
        "qs_rank": 68,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Business", "Medicine", "Law", "Computer Science"],
        "deadline": "2027-03-31",
        "has_scholarship": True,
        "tuition_usd": 4000,
    },
    # India
    {
        "name": "IIT Bombay",
        "country": "India",
        "qs_rank": 118,
        "acceptance_rate": 0.01,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Computer Science", "Mathematics", "Physics", "Design"],
        "deadline": "2027-04-30",
        "has_scholarship": True,
        "tuition_usd": 3000,
    },
    {
        "name": "IIT Delhi",
        "country": "India",
        "qs_rank": 150,
        "acceptance_rate": 0.01,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Computer Science", "Mathematics", "Physics", "Economics"],
        "deadline": "2027-04-30",
        "has_scholarship": True,
        "tuition_usd": 3000,
    },
    {
        "name": "Indian Institute of Science",
        "country": "India",
        "qs_rank": 225,
        "acceptance_rate": 0.02,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.8,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Sciences", "Physics", "Chemistry", "Mathematics"],
        "deadline": "2027-04-30",
        "has_scholarship": True,
        "tuition_usd": 2500,
    },
    # Middle East
    {
        "name": "King Abdullah University of Science and Technology",
        "country": "Saudi Arabia",
        "qs_rank": 101,
        "acceptance_rate": 0.15,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Computer Science", "Biological Sciences", "Environmental Science", "Applied Mathematics"],
        "deadline": "2027-01-15",
        "has_scholarship": True,
        "tuition_usd": 0,
    },
    {
        "name": "American University of Beirut",
        "country": "Lebanon",
        "qs_rank": 228,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.4,
        "min_ielts": 6.0,
        "majors": ["Medicine", "Engineering", "Business", "Arts", "Sciences"],
        "deadline": "2027-02-01",
        "has_scholarship": True,
        "tuition_usd": 20000,
    },
    {
        "name": "Khalifa University",
        "country": "UAE",
        "qs_rank": 279,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Computer Science", "Aerospace", "Medicine", "Sciences"],
        "deadline": "2027-03-01",
        "has_scholarship": True,
        "tuition_usd": 15000,
    },
    # Israel
    {
        "name": "Technion Israel Institute of Technology",
        "country": "Israel",
        "qs_rank": 233,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.6,
        "min_ielts": 6.5,
        "majors": ["Engineering", "Computer Science", "Architecture", "Physics", "Medicine"],
        "deadline": "2027-03-01",
        "has_scholarship": True,
        "tuition_usd": 12000,
    },
    # Turkey
    {
        "name": "Middle East Technical University",
        "country": "Turkey",
        "qs_rank": 470,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.4,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Computer Science", "Architecture", "Economics", "International Relations"],
        "deadline": "2027-06-01",
        "has_scholarship": True,
        "tuition_usd": 3000,
    },
    # New Zealand
    {
        "name": "University of Auckland",
        "country": "New Zealand",
        "qs_rank": 68,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.5,
        "majors": ["Business", "Engineering", "Law", "Medicine", "Arts"],
        "deadline": "2026-12-01",
        "has_scholarship": True,
        "tuition_usd": 30000,
    },
    # Latin America
    {
        "name": "Universidad de Buenos Aires",
        "country": "Argentina",
        "qs_rank": 393,
        "acceptance_rate": 0.90,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.0,
        "min_ielts": 6.0,
        "majors": ["Law", "Medicine", "Economics", "Engineering", "Social Sciences"],
        "deadline": "2027-03-01",
        "has_scholarship": False,
        "tuition_usd": 0,
    },
    {
        "name": "Universidade de São Paulo",
        "country": "Brazil",
        "qs_rank": 115,
        "acceptance_rate": 0.10,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Medicine", "Law", "Economics", "Architecture"],
        "deadline": "2027-01-15",
        "has_scholarship": False,
        "tuition_usd": 0,
    },
    {
        "name": "Tecnológico de Monterrey",
        "country": "Mexico",
        "qs_rank": 178,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.0,
        "majors": ["Business", "Engineering", "Computer Science", "Architecture", "Design"],
        "deadline": "2027-05-01",
        "has_scholarship": True,
        "tuition_usd": 12000,
    },

    # New countries (batch 3)
    {
        "name": "Nazarbayev University",
        "country": "Kazakhstan",
        "qs_rank": 701,
        "acceptance_rate": 0.15,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.5,
        "min_ielts": 6.5,
        "majors": ["Computer Science", "Engineering", "Business", "Medicine", "Economics"],
        "deadline": "2027-03-01",
        "has_scholarship": True,
        "tuition_usd": 14500,
    },
    {
        "name": "University of Warsaw",
        "country": "Poland",
        "qs_rank": 262,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Economics", "Law", "Political Science", "International Relations", "Mathematics"],
        "deadline": "2027-06-01",
        "has_scholarship": True,
        "tuition_usd": 4000,
    },
    {
        "name": "Charles University",
        "country": "Czech Republic",
        "qs_rank": 288,
        "acceptance_rate": 0.45,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Medicine", "Law", "Economics", "Biology", "Psychology"],
        "deadline": "2027-04-30",
        "has_scholarship": False,
        "tuition_usd": 6000,
    },
    {
        "name": "Universidade de Lisboa",
        "country": "Portugal",
        "qs_rank": 356,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.2,
        "min_ielts": 6.0,
        "majors": ["Business", "Engineering", "Law", "Economics", "Architecture"],
        "deadline": "2027-07-01",
        "has_scholarship": False,
        "tuition_usd": 7000,
    },
    {
        "name": "National Technical University of Athens",
        "country": "Greece",
        "qs_rank": 447,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Architecture", "Computer Science", "Mathematics", "Physics"],
        "deadline": "2027-06-15",
        "has_scholarship": False,
        "tuition_usd": 1500,
    },
    {
        "name": "Eötvös Loránd University",
        "country": "Hungary",
        "qs_rank": 601,
        "acceptance_rate": 0.55,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.2,
        "min_ielts": 6.0,
        "majors": ["Computer Science", "Mathematics", "Physics", "Law", "Economics"],
        "deadline": "2027-06-01",
        "has_scholarship": True,
        "tuition_usd": 5000,
    },
    {
        "name": "Qatar University",
        "country": "Qatar",
        "qs_rank": 355,
        "acceptance_rate": 0.50,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Business", "Medicine", "Law", "Computer Science"],
        "deadline": "2027-05-01",
        "has_scholarship": True,
        "tuition_usd": 8000,
    },
    {
        "name": "American University in Cairo",
        "country": "Egypt",
        "qs_rank": 401,
        "acceptance_rate": 0.60,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.2,
        "min_ielts": 6.5,
        "majors": ["Business", "Engineering", "Political Science", "Economics", "International Relations"],
        "deadline": "2027-02-01",
        "has_scholarship": True,
        "tuition_usd": 26000,
    },
    {
        "name": "University of Cape Town",
        "country": "South Africa",
        "qs_rank": 171,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.4,
        "min_ielts": 6.5,
        "majors": ["Business", "Engineering", "Law", "Medicine", "Psychology"],
        "deadline": "2027-09-30",
        "has_scholarship": True,
        "tuition_usd": 9000,
    },
    {
        "name": "Pontificia Universidad Católica de Chile",
        "country": "Chile",
        "qs_rank": 127,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Business", "Law", "Economics", "Architecture"],
        "deadline": "2027-01-10",
        "has_scholarship": True,
        "tuition_usd": 9000,
    },
    {
        "name": "Universidad de los Andes",
        "country": "Colombia",
        "qs_rank": 199,
        "acceptance_rate": 0.45,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Business", "Engineering", "Economics", "Law", "Design"],
        "deadline": "2027-04-15",
        "has_scholarship": True,
        "tuition_usd": 12000,
    },
    {
        "name": "University of Indonesia",
        "country": "Indonesia",
        "qs_rank": 206,
        "acceptance_rate": 0.15,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Business", "Law", "Medicine", "Engineering", "Economics"],
        "deadline": "2027-06-01",
        "has_scholarship": True,
        "tuition_usd": 3000,
    },
    {
        "name": "University of Malaya",
        "country": "Malaysia",
        "qs_rank": 65,
        "acceptance_rate": 0.35,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Business", "Medicine", "Computer Science", "Law"],
        "deadline": "2027-05-01",
        "has_scholarship": True,
        "tuition_usd": 5500,
    },
    {
        "name": "Chulalongkorn University",
        "country": "Thailand",
        "qs_rank": 211,
        "acceptance_rate": 0.30,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Business", "Engineering", "Medicine", "Economics", "Law"],
        "deadline": "2027-03-01",
        "has_scholarship": True,
        "tuition_usd": 4500,
    },
    {
        "name": "Vietnam National University, Hanoi",
        "country": "Vietnam",
        "qs_rank": 851,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.2,
        "min_ielts": 5.5,
        "majors": ["Computer Science", "Engineering", "Business", "Economics", "Law"],
        "deadline": "2027-06-01",
        "has_scholarship": True,
        "tuition_usd": 3000,
    },
    {
        "name": "University of the Philippines Diliman",
        "country": "Philippines",
        "qs_rank": 401,
        "acceptance_rate": 0.15,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Business", "Political Science", "Economics", "Law"],
        "deadline": "2027-03-31",
        "has_scholarship": True,
        "tuition_usd": 2000,
    },
    {
        "name": "Lahore University of Management Sciences",
        "country": "Pakistan",
        "qs_rank": 421,
        "acceptance_rate": 0.15,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.5,
        "majors": ["Business", "Computer Science", "Economics", "Law", "Engineering"],
        "deadline": "2027-05-15",
        "has_scholarship": True,
        "tuition_usd": 9000,
    },
    {
        "name": "University of Iceland",
        "country": "Iceland",
        "qs_rank": 501,
        "acceptance_rate": 0.60,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.2,
        "min_ielts": 6.0,
        "majors": ["Engineering", "Biology", "Economics", "Law", "Design"],
        "deadline": "2027-06-05",
        "has_scholarship": False,
        "tuition_usd": 700,
    },
    {
        "name": "University of Luxembourg",
        "country": "Luxembourg",
        "qs_rank": 305,
        "acceptance_rate": 0.40,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.3,
        "min_ielts": 6.0,
        "majors": ["Business", "Law", "Computer Science", "Economics", "Mathematics"],
        "deadline": "2027-04-30",
        "has_scholarship": True,
        "tuition_usd": 800,
    },
    {
        "name": "Lomonosov Moscow State University",
        "country": "Russia",
        "qs_rank": 87,
        "acceptance_rate": 0.20,
        "sat_25th": None,
        "sat_75th": None,
        "avg_gpa": 3.4,
        "min_ielts": 6.0,
        "majors": ["Mathematics", "Physics", "Economics", "Law", "Biology"],
        "deadline": "2027-07-01",
        "has_scholarship": True,
        "tuition_usd": 7000,
    },
]


def main():
    print(f"Заполняем базу: {len(UNIVERSITIES)} университетов...")
    inserted = 0
    skipped = 0

    for uni in UNIVERSITIES:
        # Убираем None-значения чтобы не перезаписывать существующие
        payload = {k: v for k, v in uni.items() if v is not None}
        try:
            existing = (
                supabase.table("universities")
                .select("id")
                .eq("name", uni["name"])
                .eq("country", uni["country"])
                .execute()
            )
            if existing.data:
                print(f"  SKIP  {uni['name']} (уже есть)")
                skipped += 1
            else:
                supabase.table("universities").insert(payload).execute()
                print(f"  OK    {uni['name']} ({uni['country']})")
                inserted += 1
        except Exception as e:
            print(f"  ERR   {uni['name']}: {e}")

    print(f"\nГотово: вставлено {inserted}, пропущено {skipped}")


if __name__ == "__main__":
    main()
